name = "EssentialTFC"
author = "Gaelmare"
version = "3.0.7"
description = "Beginner's TerraFirmaCraft modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afb46cc39fcfc542280d8de8ae3072b492f84e0517863f290c9ab814da151e79"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
