#The default difficulty selected for newly created worlds.
#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
defaultDifficulty = "NORMAL"
#Resource pack IDs to have enabled by default on the first run.
defaultResourcePacks = ["vanilla", "mod_resources", "fabric", "file/Vexxed_Visuals_TFC_v1.3.8.zip", "file/Vexxed Visuals - TFC Canes.zip", "file/TFC_Aures_Livestock_Skins_1.0.zip"]
#Set to true if the difficulty for new world's should be locked to the specific default. This cannot be unlocked by players without external tools! Probably a bad idea. I don't recommend. Why am I adding this option?
lockDifficulty = false
